version: "3.7"
name: purity-vision
secrets:
  google_credentials:
    file: secrets/google-credentials.json
services:
  api:
    image: purity-vision:latest
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "8080:8080"
    secrets:
      - google_credentials
    environment:
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_credentials
      - PURITY_DB_HOST=${PURITY_DB_HOST}
      - PURITY_DB_PORT=${PURITY_DB_PORT}
      - PURITY_DB_NAME=${PURITY_DB_NAME}
      - PURITY_DB_USER=${PURITY_DB_USER}
      - PURITY_DB_PASS=${PURITY_DB_PASS}
      - PURITY_DB_SSL_MODE=${PURITY_DB_SSL_MODE}
      - PURITY_LOG_LEVEL=${PURITY_LOG_LEVEL}
      - STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_SECRET}
      - STRIPE_KEY=${STRIPE_KEY}
      - EMAIL_NAME=${EMAIL_NAME}
      - EMAIL_FROM=${EMAIL_FROM}
      - SENDGRID_API_KEY=${SENDGRID_API_KEY}
  db:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./pg-data:/var/lib/postgresql/data"
      - "./migrations:/docker-entrypoint-initdb.d"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${PURITY_DB_USER}",
          "-d",
          "${PURITY_DB_NAME}"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
