version: "3.7"
name: purity-vision
secrets:
  google_credentials:
    file: ./google-credentials.json
services:
  web:
    image: gradeycullins/purity-vision:latest
    pull_policy: always
    depends_on:
      db:
        condition: service_healthy
    links:
      - db
    ports:
      - "9090:8080"
    secrets:
      - google_credentials
    environment:
      - PURITY_DB_HOST=${PURITY_DB_HOST}
      - PURITY_DB_PORT=${PURITY_DB_PORT}
      - PURITY_DB_NAME=${PURITY_DB_NAME}
      - PURITY_DB_USER=${PURITY_DB_USER}
      - PURITY_DB_PASS=${PURITY_DB_PASS}
      - PURITY_DB_SSL_MODE=${PURITY_DB_SSL_MODE}
      - GOOGLE_APPLICATION_CREDENTIALS=/run/secrets/google_credentials
      - PURITY_LOG_LEVEL=${PURITY_LOG_LEVEL}
  db:
    image: postgres:latest
    hostname: postgres
    ports:
      - "5432:5432"
    volumes:
      - "./pg-data:/var/lib/postgresql/data"
      - "./migrations:/docker-entrypoint-initdb.d"
    healthcheck:
      test:
        [
          "CMD",
          "pg_isready",
          "-U",
          "${PURITY_DB_USER}",
          "-d",
          "${PURITY_DB_NAME}"
        ]
      interval: 10s
      timeout: 5s
      retries: 3
networks:
  default:
    external: true
    name: 'gnas-npm'
